from rsf.proj import *


Result('rfl_p',
       '''
	   byte gainpanel=all clip=1e2 bar=bar.rsf|
       grey3 title="PP image" 
       color=i scalebar=y barreverse=y
	   maxval=1e2 minval=-1e2
       flat=y frame1=90 frame2=160 frame3=160 
       ''')

Result('rfl_s',
       '''
	   byte gainpanel=all clip=1e2 bar=bar.rsf|
       grey3 title="PS image" 
       color=i scalebar=y barreverse=y
	   maxval=1e2 minval=-1e2
       flat=y frame1=90 frame2=160 frame3=160 
       ''')

Result('model',
       '''
	   byte gainpanel=all maxval=6 minval=2 bias=4 bar=bar.rsf|
       grey3 title="The model" 
       color=i scalebar=y barlabel="P-wave velocity (m/s)"
	   maxval=6 minval=2 bias=4
       flat=y frame1=90 frame2=160 frame3=160 

       ''')
End()

#Result('rfl_p',
#       '''
#       laplac3 | grey title="PP image" clip=3e-5 
#       color=i gainpanel=a barreverse=y
#       ''')
#End()
